const WebSocket = require("ws");
function makeClient(label){return new Promise(resolve=>{const ws=new WebSocket("ws://localhost:3000");const events=[];ws.on("open",()=>resolve({ws,events,label}));ws.on("message",raw=>{events.push(JSON.parse(raw.toString()));});ws.on("error",e=>console.error("["+label+"] err",e.message));});}
function send(ws,event,data){ws.send(JSON.stringify({event,data:data||{}}));}
function wait(ms){return new Promise(r=>setTimeout(r,ms));}
function last(ev,n){return [...ev].reverse().find(e=>e.event===n);}
function firstWith(ev,n,pred){return ev.find(e=>e.event===n&&pred(e));}
let passed=0,failed=0;
function check(label,ok,note){console.log("  "+(ok?"PASS":"FAIL")+" "+label+(note?" ("+note+")":""));if(ok)passed++;else failed++;return ok;}
async function run(){
  console.log("=== LIFECYCLE VERIFICATION ===");
  const host=await makeClient("HOST"),player=await makeClient("PLAYER");
  send(host.ws,"create_room",{displayName:"HostUser"});await wait(150);
  const roomCode=firstWith(host.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)?.data?.code;
  const hostId=firstWith(host.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)?.data?.localPlayerId;
  send(player.ws,"join_room",{roomCode,displayName:"PlayerUser"});await wait(150);
  const playerId=firstWith(player.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)?.data?.localPlayerId;
  console.log("Room:",roomCode,"hostId:",hostId&&hostId.slice(0,6),"playerId:",playerId&&playerId.slice(0,6));
  send(host.ws,"start_game");await wait(250);
  const hGame=firstWith(host.events,"game_state",e=>!!e.data&&!!e.data.localPlayerId);
  const pGame=firstWith(player.events,"game_state",e=>!!e.data&&!!e.data.localPlayerId);
  console.log("[Case 1]");
  check("Case1 host localPlayerId in game_state",hGame&&hGame.data.localPlayerId===hostId);
  check("Case1 player localPlayerId in game_state",pGame&&pGame.data.localPlayerId===playerId);
  console.log("[Cases 2/3/10] player exits");
  const hBefore=host.events.length;
  send(player.ws,"exit_game_to_home");await wait(350);
  const hRoomExit=last(host.events,"room_update");
  const hGameExit=last(host.events,"game_state");
  const pInRoom=hRoomExit&&hRoomExit.data.players&&hRoomExit.data.players.find(p=>p.id===playerId);
  const pInGame=hGameExit&&hGameExit.data.players&&hGameExit.data.players.find(p=>p.id===playerId);
  check("Case2 host gets room_update after exit",host.events.length>hBefore&&!!hRoomExit);
  check("Case2 host gets game_state after exit",!!hGameExit);
  check("Case2 player kept in room",!!pInRoom,"isConnected="+(pInRoom&&pInRoom.isConnected));
  check("Case10 room_update shows disconnected",pInRoom&&pInRoom.isConnected===false);
  check("Case10 game_state shows disconnected",pInGame&&pInGame.isConnected===false);
  console.log("[Cases 4/5] isolation");
  const pBefore=player.events.length;
  send(host.ws,"lock_room");await wait(200);send(host.ws,"unlock_room");await wait(200);
  check("Case4+5 no broadcasts to exited player",player.events.length===pBefore,"delta="+(player.events.length-pBefore));
  console.log("[Cases 6/7] reconnect");
  const p2=await makeClient("REJOIN");
  send(p2.ws,"check_presence",{playerId,roomCode});await wait(350);
  const p2Room=last(p2.events,"room_update");
  const p2Game=last(p2.events,"game_state");
  const p2Err=last(p2.events,"error");
  if(p2Err)console.log("  server error:",JSON.stringify(p2Err.data));
  const pReconn=last(host.events,"room_update")&&last(host.events,"room_update").data.players&&last(host.events,"room_update").data.players.find(p=>p.id===playerId);
  check("Case6 reconnect gets room_update",!!p2Room);
  check("Case6 reconnect gets game_state",!!p2Game);
  check("Case6 game_state localPlayerId correct",p2Game&&p2Game.data&&p2Game.data.localPlayerId===playerId,"got="+(p2Game&&p2Game.data&&p2Game.data.localPlayerId&&p2Game.data.localPlayerId.slice(0,6)||"none"));
  check("Case6 host sees player reconnected",pReconn&&pReconn.isConnected===true);
  console.log("[Case 8] permanent leave");
  send(p2.ws,"exit_game_to_home");await wait(200);
  const perm=await makeClient("PERM");
  send(perm.ws,"leave_game_permanently",{playerId,roomCode});await wait(350);
  const hRoomPerm=last(host.events,"room_update");
  const hGamePerm=last(host.events,"game_state");
  check("Case8 removed from room_update",!(hRoomPerm&&hRoomPerm.data.players&&hRoomPerm.data.players.find(p=>p.id===playerId)));
  check("Case8 removed from game_state",!(hGamePerm&&hGamePerm.data.players&&hGamePerm.data.players.find(p=>p.id===playerId)));
  console.log("[Case 9] host perm leave + transfer");
  const h2=await makeClient("H2"),p3=await makeClient("P3");
  send(h2.ws,"create_room",{displayName:"HostTwo"});await wait(150);
  const h2Code=firstWith(h2.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)&&firstWith(h2.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId).data.code;
  const h2Id=firstWith(h2.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)&&firstWith(h2.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId).data.localPlayerId;
  send(p3.ws,"join_room",{roomCode:h2Code,displayName:"P3"});await wait(150);
  const p3Id=firstWith(p3.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)&&firstWith(p3.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId).data.localPlayerId;
  send(h2.ws,"start_game");await wait(200);
  send(h2.ws,"exit_game_to_home");await wait(200);
  const h2perm=await makeClient("H2PERM");
  send(h2perm.ws,"leave_game_permanently",{playerId:h2Id,roomCode:h2Code});await wait(350);
  const p3Room=last(p3.events,"room_update");
  const oldGone=!(p3Room&&p3Room.data.players&&p3Room.data.players.find(p=>p.id===h2Id));
  const newHost=p3Room&&p3Room.data.players&&p3Room.data.players.find(p=>p.isHost);
  check("Case9 old host removed",oldGone);
  check("Case9 host transferred to p3",newHost&&newHost.id===p3Id,"new="+(newHost&&newHost.displayName));
  console.log("[Case 11] broadcast immediate (web sim)");
  const hW=await makeClient("HW"),pW=await makeClient("PW");
  send(hW.ws,"create_room",{displayName:"WebHost"});await wait(150);
  const wCode=firstWith(hW.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)&&firstWith(hW.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId).data.code;
  send(pW.ws,"join_room",{roomCode:wCode,displayName:"WebPlayer"});await wait(150);
  const wPId=firstWith(pW.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)&&firstWith(pW.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId).data.localPlayerId;
  send(hW.ws,"start_game");await wait(200);
  const hWBefore=hW.events.length;
  send(pW.ws,"exit_game_to_home");await wait(300);
  const hWRoom=last(hW.events,"room_update");
  const hWGame=last(hW.events,"game_state");
  const wPInRoom=hWRoom&&hWRoom.data.players&&hWRoom.data.players.find(p=>p.id===wPId);
  check("Case11 observer gets room_update",hW.events.length>hWBefore&&!!hWRoom);
  check("Case11 observer gets game_state",!!hWGame);
  check("Case11 observer sees disconnected",wPInRoom&&wPInRoom.isConnected===false);
  console.log("[Case 12] 2x leave/rejoin cycles");
  const hC=await makeClient("HC"),pC=await makeClient("PC");
  send(hC.ws,"create_room",{displayName:"CHost"});await wait(150);
  const cCode=firstWith(hC.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)&&firstWith(hC.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId).data.code;
  send(pC.ws,"join_room",{roomCode:cCode,displayName:"CPly"});await wait(150);
  const cPId=firstWith(pC.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId)&&firstWith(pC.events,"room_update",e=>!!e.data&&!!e.data.localPlayerId).data.localPlayerId;
  send(hC.ws,"start_game");await wait(200);
  send(pC.ws,"exit_game_to_home");await wait(150);
  const c2=await makeClient("C2");
  send(c2.ws,"check_presence",{playerId:cPId,roomCode:cCode});await wait(200);
  send(c2.ws,"exit_game_to_home");await wait(150);
  const c3=await makeClient("C3");
  send(c3.ws,"check_presence",{playerId:cPId,roomCode:cCode});await wait(200);
  const c3GCount=c3.events.filter(e=>e.event==="game_state").length;
  const c3RCount=c3.events.filter(e=>e.event==="room_update").length;
  check("Case12 no dup game_state after 2 cycles",c3GCount===1,"got "+c3GCount);
  check("Case12 no dup room_update after 2 cycles",c3RCount<=2,"got "+c3RCount);
  const cInRoom=last(hC.events,"room_update")&&last(hC.events,"room_update").data.players&&last(hC.events,"room_update").data.players.find(p=>p.id===cPId);
  check("Case12 player connected after 2 cycles",cInRoom&&cInRoom.isConnected===true);
  console.log("=== "+passed+"/"+(passed+failed)+" passed ===");
  [host,player,p2,perm,h2,h2perm,p3,hW,pW,hC,pC,c2,c3].forEach(c=>{try{c.ws.close();}catch(_){}});
  process.exit(failed>0?1:0);
}
run().catch(e=>{console.error(e);process.exit(1);});
